

version: '3.7'

services:
  psql:
    image: postgres
    container_name: 'postgra'
    volumes:
      - ./migrations/migration.sql:/docker-entrypoint-initdb.d/migration.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  app:
    container_name: 'my-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - psql