version: '3.7'

services:
  psql:
    image: postgres
    container_name: 'postgra'
    volumes:
      - ./migrations/migration.sql:/docker-entrypoint-initdb.d/migration.sql:ro
    ports:
      - "${db_port}:${db_port}"
    environment:
      - POSTGRES_USER=${db_login}
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_DB=books

  app:
    container_name: 'my-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - psql